site_name: Essetee

nav:
  - Home: index.md
  - Linux Topics:
    - 'ssh met publieke sleutel': ssh.md
    - 'Debian VirtualBox installatie': vboxdebian.md
  - Python:
    - 'QtDesigner': qtdesigner.md
    - 'Create a blank pyside6 Mainwindow': blank_template_pyside6_mainwindow.md


theme:
  name: material
  logo: logo.png
